module.exports = {
  equals: 'Not equal',
  contains: 'Invalid characters',
  matches: 'Does not match',
  isEmail: 'Invalid email',
  isUrl: 'Invalid URL',
  isFQDN: 'Invalid FQDN',
  isIP: 'Invalid IP',
  isAlpha: 'Invalid characters',
  isNumeric: 'Invalid number',
  isAlphanumeric: 'Invalid characters',
  isBase64: 'Invalid base64',
  isHexadecimal: 'Invalid hexadecimal',
  isHexColor: 'Invalid hexcolor',
  isLowercase: 'Invalid characters',
  isUppercase: 'Invalid characters',
  isInt: 'Invalid integer',
  isFloat: 'Invalid float',
  isDivisibleBy: 'Not divisible',
  isNull: 'String is not empty',
  isLength: 'String is not in range',
  isByteLength: 'Invalid byte length',
  isUUID: 'Invalid UUID',
  isDate: 'Invalid date',
  isAfter: 'Invalid date',
  isBefore: 'Invalid date',
  isIn: 'Unexpected value or invalid argument',
  isCreditCard: 'Invalid credit card',
  isISBN: 'Invalid ISBN',
  isJSON: 'Invalid JSON',
  isMultibyte: 'Invalid Multibyte',
  isAscii: 'Invalid ASCII characters',
  isFullWidth: 'Does not contains full-width chars',
  isHalfWidth: 'Does not contains half-width chars',
  isVariableWidth: 'Does not contains a mixture of full and half-width chars',
  isSurrogatePair: 'Does not contains any surrogate pairs chars',
  isBoolean: 'Invalid boolean',
  isCurrency: 'Invalid currency',
  isISIN: 'Invalid ISIN',
  isMobilePhone: 'Invalid mobile phone number',
  isMongoId: 'Invalid MongoDB ID'
}
