name: Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: docker-compose up -d
      - run: npm install
      - run: npm run format:ci
      - run: npm test
